# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.create(manufacturer: 'Dodge', model: 'Ram 1500', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus nisi veritatis iusto eveniet. Quae sed quia est. Voluptatibus, atque nam ipsam veniam illum repellendus, quas aperiam labore libero harum molestiae!', 										picture: File.new("db/seed-images/ram1500.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'Mustang', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo laudantium omnis numquam, aliquam voluptatem expedita quidem ipsum dolorum! Perferendis ducimus nobis, maiores explicabo facilis asperiores eveniet quae quam minus earum.', 						picture: File.new("db/seed-images/mustang.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Camaro', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus aliquid suscipit, ullam nobis expedita non, placeat velit dolore quibusdam ipsa, natus nesciunt cum voluptatem corporis vero praesentium obcaecati adipisci quas.', 							picture: File.new("db/seed-images/camaro.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Dodge', model: 'Viper', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid, harum quaerat doloribus cumque ratione porro non iste, voluptatum molestiae nemo laborum ea quisquam ullam dolorum. Mollitia, beatae repellendus! Odio!', 								picture: File.new("db/seed-images/viper.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'F-150', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt cumque amet, officiis suscipit? Illum, aliquid expedita eaque explicabo, vero incidunt eos, saepe quia nostrum similique est magnam excepturi sed veniam.', 									picture: File.new("db/seed-images/f150.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Corvette', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo non sapiente explicabo ex quo aperiam commodi laboriosam assumenda ducimus sit, facilis placeat laudantium rem, adipisci voluptate omnis tenetur dolore optio.', 								picture: File.new("db/seed-images/corvette.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Dodge', model: 'Dart', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis maxime ratione nobis dolores est ex facere assumenda quis aliquam, possimus ipsum expedita quo, veniam quas eaque voluptas quos nihil illo.', 													picture: File.new("db/seed-images/dart.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'F-250', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente nostrum eum commodi similique, ipsa eveniet sint accusamus placeat voluptates nesciunt dolorem minima molestias corrupti aliquid dolore odio! Dolores, ipsum voluptatibus!', 					picture: File.new("db/seed-images/f250.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Silverado', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis distinctio ratione dolore accusantium numquam dolor, illum vitae doloremque aperiam? Veritatis ipsum ratione reiciendis expedita voluptas nostrum consectetur quasi aut. Temporibus.', 		picture: File.new("db/seed-images/silverado.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Dodge', model: 'Charger', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore saepe ad exercitationem blanditiis, assumenda amet necessitatibus, quas sint voluptate fugiat. Id non magnam porro voluptatum! Atque obcaecati, suscipit deleniti? Qui!', 						picture: File.new("db/seed-images/charger.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'Escape', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia eveniet non cum enim fugit consequatur laudantium consequuntur! Neque corrupti sapiente quaerat sunt ducimus repellendus a! Vel inventore at quis porro.', 										picture: File.new("db/seed-images/escape.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Impala', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam corrupti, cum et veniam rerum possimus vitae laborum. Voluptatibus ullam minima molestiae quam, sit numquam vel optio. Laboriosam obcaecati quia mollitia!', 									picture: File.new("db/seed-images/impala.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Dodge', model: 'Challenger', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident corporis repellat quia maxime et earum quasi, harum, aspernatur rerum repudiandae, quo voluptate enim itaque cum fugiat autem illo tempora dolor!', 										picture: File.new("db/seed-images/challenger.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'Focus', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia iure, ratione totam consequatur corporis asperiores in nisi ipsa aut omnis esse eius vero dignissimos cupiditate deleniti excepturi veritatis labore laboriosam.', 									picture: File.new("db/seed-images/focus.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Cruze', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis veniam assumenda corporis doloribus repellendus, quam eveniet consectetur quos similique provident natus, culpa consequatur quae in minus, rerum delectus. Odit, facilis!', 					picture: File.new("db/seed-images/cruze.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Dodge', model: 'Ram 3500', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam voluptatibus earum, totam praesentium aperiam, at! Explicabo, ipsum expedita laboriosam commodi dicta reprehenderit incidunt, adipisci voluptas enim, libero consequuntur nemo rem!', 		picture: File.new("db/seed-images/ram3500.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Ford', model: 'Fusion', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio doloremque nulla nisi eos, enim saepe blanditiis, beatae labore tenetur delectus alias nostrum asperiores itaque. Repudiandae natus eum fugit nulla facere.', 								picture: File.new("db/seed-images/fusion.jpg"), price: rand(20000..60000))
Post.create(manufacturer: 'Chevy', model: 'Malibu', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore recusandae hic dolores illo quae fugiat, accusantium nulla. Minus tenetur tempore doloribus obcaecati perferendis, molestiae, laudantium, reprehenderit laborum, distinctio rem quaerat.', 	picture: File.new("db/seed-images/malibu.jpg"), price: rand(20000..60000))





